using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace PsychoTest.Tests.ConfusedLines
{
    /// <summary>
    /// Interaction logic for Statistics.xaml
    /// </summary>
    public partial class Statistics : Window
    {
        public Statistics()
        {
            InitializeComponent();

            UpdateGrid();
        }

        private void UpdateGrid()
        {
            using (var context = new Model.DB())
            {
                var querry = from r in context.ConfusedLinesTestResults
                             select new
                             {
                                 ResultId = r.ResultId,
                                 Name = r.Name,
                                 Date = r.Date,
                                 ErrorsCount = r.ErrorsCount,
                                 Time = r.Time,
                                 Result = r.Result
                             };
                dataGrid.ItemsSource = querry.ToList();
                dataGrid.ColumnWidth = DataGridLength.Auto;


            }
        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid.Columns[0].Visibility = Visibility.Hidden;
            dataGrid.Columns[1].Header = "Ім'я";
            dataGrid.Columns[2].Header = "Дата і час";
            dataGrid.Columns[3].Header = "Кількість помилок";
            dataGrid.Columns[4].Header = "Витрачений час";
            dataGrid.Columns[5].Header = "Результат";
        }

        private void deleteButton_Click(object sender, RoutedEventArgs e)
        {
            using (var context = new Model.DB())
            {
                var resultId = (int)((dynamic)dataGrid.SelectedItems[0]).ResultId;
                var result = context.ConfusedLinesTestResults.First(r => r.ResultId == resultId);
                context.ConfusedLinesTestResults.Remove(result);
                context.SaveChanges();
            }

            UpdateGrid();
        }

        private void importButton_Click(object sender, RoutedEventArgs e)
        {
            var app = new Microsoft.Office.Interop.Excel.Application();
            var workbook = app.Workbooks.Add();
            var worksheet = workbook.Worksheets[1];
            worksheet.Cells[1, 1] = "Ім'я";
            worksheet.Cells[1, 2] = "Дата і час";
            worksheet.Cells[1, 3] = "Кількість помилок";
            worksheet.Cells[1, 4] = "Витрачений час";
            worksheet.Cells[1, 5] = "Результат";

            using (var context = new Model.DB())
            {
                var results = context.ConfusedLinesTestResults.ToList();
                for (int i = 0; i < results.Count(); i++)
                {
                    worksheet.Cells[i + 2, 1] = results[i].Name;
                    worksheet.Cells[i + 2, 2] = results[i].Date;
                    worksheet.Cells[i + 2, 3] = results[i].ErrorsCount;
                    worksheet.Cells[i + 2, 4] = results[i].Time;
                    worksheet.Cells[i + 2, 5] = results[i].Result;
                }
            }

            app.Visible = true;
        }
    }
}
